from enum import Enum

class CaliDependency(str, Enum):
    SALUD = "4145010"
    MOVILIDAD = "4152010"
    JURIDICA = "4121010"
    INFRAESTRUCTURA = "4151010"
    HACIENDA = "4131010"
    EDUCACION = "4143010"
    SEGURIDAD = "4161010"
    CULTURA = "4148010"
    GENERAL = "4111010"

DEPENDENCY_NAMES = {
    CaliDependency.SALUD: "SECRETARIA DE SALUD",
    CaliDependency.MOVILIDAD: "SECRETARIA DE MOVILIDAD",
    CaliDependency.JURIDICA: "GESTION JURIDICA PUBLICA",
    CaliDependency.INFRAESTRUCTURA: "SECRETARIA DE INFRAESTRUCTURA",
    CaliDependency.HACIENDA: "SECRETARIA DE HACIENDA",
    CaliDependency.EDUCACION: "SECRETARIA DE EDUCACION",
    CaliDependency.SEGURIDAD: "SECRETARIA DE SEGURIDAD Y JUSTICIA",
    CaliDependency.CULTURA: "SECRETARIA DE CULTURA",
    CaliDependency.GENERAL: "SECRETARIA DE GOBIERNO"
}

HIGH_PRIORITY_DEPENDENCIES = [CaliDependency.SALUD, CaliDependency.JURIDICA, CaliDependency.SEGURIDAD]
